name: Build and deploy the toolbox image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "righettod/toolbox-jsoncrack"
  PLATFORM: "linux/amd64"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List content from checkout
        run: chmod +x build.sh; bash build.sh
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: jsoncrack
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
